name: bsmp
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - accelerate=1.3.0
  - adwaita-icon-theme=47.0
  - appnope=0.1.4
  - arviz=0.20.0
  - asttokens=3.0.0
  - atk-1.0=2.36.0
  - attrs=24.3.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - beautifulsoup4=4.12.3
  - blas=2.129
  - blas-devel=3.9.0
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.1
  - cairo=1.16.0
  - cctools_osx-arm64=949.0.1
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - clang=14.0.6
  - clang-14=14.0.6
  - clang_osx-arm64=14.0.6
  - clangxx=14.0.6
  - clangxx_osx-arm64=14.0.6
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - compiler-rt=14.0.6
  - compiler-rt_osx-arm64=14.0.6
  - cons=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - debugpy=1.8.12
  - decorator=5.1.1
  - deprecated=1.2.13
  - epoxy=1.5.10
  - etuples=0.3.9
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2025.2.0
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - gflags=2.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gobject-introspection=1.78.1
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gtk3=3.24.21
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.2.0
  - h5netcdf=1.5.0
  - h5py=3.12.1
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - huggingface_hub=0.28.0
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - importlib-metadata=7.0.1
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.12
  - ld64_osx-arm64=530
  - ldid=2.1.5
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=16.1.0
  - libasprintf=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp14=14.0.6
  - libcrc32c=1.1.2
  - libcurl=8.12.0
  - libcxx=19.1.7
  - libcxx-devel=18.1.8
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgd=2.3.3
  - libgettextpo=0.23.1
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libintl=0.23.1
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - liblzma=5.6.4
  - libnghttp2=1.57.0
  - libopenblas=0.3.28
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librsvg=2.56.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libtiff=4.2.0
  - libtool=2.4.7
  - libtorch=2.5.1
  - libutf8proc=2.8.0
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.2.13
  - llvm-openmp=19.1.7
  - llvm-tools=14.0.6
  - llvmlite=0.44.0
  - logical-unification=0.4.6
  - lz4-c=1.9.4
  - macosx_deployment_target_osx-arm64=11.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minikanren=1.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - ninja=1.12.1
  - ninja-base=1.12.1
  - nomkl=1.0
  - numba=0.61.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - nutpie=0.13.3
  - openblas=0.3.28
  - openjpeg=2.4.0
  - openssl=3.4.1
  - opentelemetry-api=1.26.0
  - optree=0.12.1
  - orc=2.0.1
  - outcome=1.1.0
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=25.0.1
  - pixman=0.44.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow-core=16.1.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.1
  - pymc=5.16.1
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - pytensor=2.23.0
  - python=3.12.3
  - python-dateutil=2.9.0.post0
  - python-graphviz=0.20.3
  - python-tzdata=2025.1
  - python_abi=3.12
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - safetensors=0.4.5
  - scipy=1.12.0
  - seaborn=0.13.2
  - selenium=4.24.0
  - setuptools=75.8.0
  - sigtool=0.1.3
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.13.3
  - tapi=1100.0.11
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - trio=0.26.2
  - trio-websocket=0.11.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - websocket-client=1.8.0
  - wheel=0.45.1
  - wrapt=1.17.0
  - wsproto=1.2.0
  - xarray=2025.1.2
  - xarray-einstats=0.8.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
